"""delete time related attributes

Revision ID: f1b72949b817
Revises: 0e82b090e8cc
Create Date: 2020-01-14 19:59:37.427554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1b72949b817'
down_revision = '0e82b090e8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('member_since', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
